"""CRM-24: add deal build status and mismatch flag

Revision ID: cdf49c61fe01
Revises: b5d235a9293b
Create Date: 2026-09-17 15:34:06.354023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf49c61fe01'
down_revision = 'b5d235a9293b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('build_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mismatch_flagged', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mismatch_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('mismatch_note')
        batch_op.drop_column('mismatch_flagged')
        batch_op.drop_column('build_status')

    # ### end Alembic commands ###
