"""add requirements and budget to deals

Revision ID: dd1d6b036f7b
Revises: 2a105f7b66d2
Create Date: 2026-07-28 22:30:45.524361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1d6b036f7b'
down_revision = '2a105f7b66d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('budget')
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###
